version: '3.8'

volumes:
  messaging_postgres_data:
    driver: local

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_HOST: ${DB_HOST}
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d
      - messaging_postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A celery_app worker --loglevel=info
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app

  telegram_bot:
    build: .
    command: python telegram_bot.py
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/app

networks:
  default:
    name: nginx_network
    external: true

